<template>
  <div class="hitl-review-bar" role="region" aria-labelledby="hitl-review-title">
    <div class="hitl-review-bar__summary"><span class="hitl-icon" aria-hidden="true">!</span><div><p id="hitl-review-title">需要你的确认</p><strong>{{ draft.title }} · {{ draft.roomName }}</strong><span>{{ formatDateTime(draft.startAt) }} — {{ formatDateTime(draft.endAt) }}<template v-if="expiresAt"> · {{ formatDateTime(expiresAt) }} 前有效</template></span></div></div>
    <div class="hitl-review-bar__actions"><button class="ui-button ui-button--default" type="button" :disabled="busy" @click="$emit('accept')">{{ busy ? '处理中…' : '接受并执行' }}</button><button class="ui-button ui-button--outline" type="button" :disabled="busy" @click="editing = true">编辑后重新规划</button><button class="ui-button ui-button--ghost hitl-reject" type="button" :disabled="busy" @click="confirmReject = true">拒绝</button></div>
  </div>
  <Teleport to="body">
    <div v-if="editing" class="dialog-layer"><button class="drawer-overlay" aria-label="关闭编辑" @click="editing=false" /><section class="ui-dialog" role="dialog" aria-modal="true" aria-labelledby="edit-title"><header><div><p>HITL 编辑</p><h2 id="edit-title">修改草案并重新规划</h2></div><button class="icon-button" type="button" aria-label="关闭编辑" @click="editing=false">×</button></header><p>只允许调整会议室或开始时间；提交后会重新执行规则与可用性校验。</p><label><span>会议室 ID</span><input v-model.trim="roomId" inputmode="numeric" /></label><label><span>开始时间（Asia/Shanghai）</span><input v-model="startAt" type="datetime-local" step="1800" /></label><label><span>反馈（可选）</span><textarea :value="feedback" rows="2" maxlength="1000" @input="updateFeedback" /></label><p v-if="error" class="inline-error" role="alert">{{ error }}</p><footer><button class="ui-button ui-button--outline" type="button" @click="editing=false">取消</button><button class="ui-button ui-button--default" type="button" @click="submitEdit">重新规划</button></footer></section></div>
    <div v-if="confirmReject" class="dialog-layer"><button class="drawer-overlay" aria-label="关闭拒绝确认" @click="confirmReject=false" /><section class="ui-dialog ui-dialog--sm" role="alertdialog" aria-modal="true" aria-labelledby="reject-title"><h2 id="reject-title">拒绝这份草案？</h2><p>草案会失效，当前 Agent Run 将结束；不会占用会议室或创建正式会议。</p><footer><button class="ui-button ui-button--outline" type="button" @click="confirmReject=false">返回</button><button class="ui-button ui-button--destructive" type="button" @click="reject">确认拒绝</button></footer></section></div>
  </Teleport>
</template>
<script setup lang="ts">
import { computed, ref, watch } from 'vue'; import type { AgentDraft } from '@/api/types'; import { formatDateTime, toShanghaiDateTimeLocal, toShanghaiOffset } from '@/utils/format'; import { useModalFocus } from '@/composables/useModalFocus'
const props=defineProps<{ draft: AgentDraft; expiresAt?: string; busy: boolean; feedback: string }>(); const emit=defineEmits<{ accept: []; reject: []; edit: [changes: { roomId?: number; startAt?: string }]; 'update:feedback': [value:string] }>()
const editing=ref(false), confirmReject=ref(false), roomId=ref(''), startAt=ref(''), error=ref('')
useModalFocus(computed(() => editing.value || confirmReject.value), () => { editing.value=false; confirmReject.value=false })
watch(() => props.draft, (d) => { roomId.value=String(d.roomId); startAt.value=toShanghaiDateTimeLocal(d.startAt); error.value='' }, { immediate:true })
function updateFeedback(event: Event): void { if(event.target instanceof HTMLTextAreaElement) emit('update:feedback', event.target.value) }
function submitEdit(): void { const nextRoom=Number.parseInt(roomId.value,10), original=toShanghaiDateTimeLocal(props.draft.startAt); const changedRoom=Number.isSafeInteger(nextRoom)&&nextRoom>0&&nextRoom!==props.draft.roomId; const changedStart=/^[0-9]{4}-[0-9]{2}-[0-9]{2}T(?:[01][0-9]|2[0-3]):(?:00|30)$/.test(startAt.value)&&startAt.value!==original; if(!changedRoom&&!changedStart){error.value='请至少修改会议室或开始时间，且时间须落在 30 分钟槽位。';return} editing.value=false; emit('edit',{...(changedRoom?{roomId:nextRoom}:{}),...(changedStart?{startAt:toShanghaiOffset(startAt.value)}:{})}) }
function reject(): void { confirmReject.value=false; emit('reject') }
</script>
